CLASS LHC_ZRAP_I_EXCEL DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    TYPES: BEGIN OF TY_FILE,
             CUSTOMER TYPE ZRAP_I_EXCEL-CUSTOMER,
             ARTICLE  TYPE ZRAP_I_EXCEL-ARTICLE,
           END OF TY_FILE.
    TYPES: TT_FILE TYPE STANDARD TABLE OF TY_FILE WITH DEFAULT KEY.
    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST requested_authorizations FOR EXCEL RESULT result.

    METHODS FILEUPLOAD FOR MODIFY
      IMPORTING KEYS FOR ACTION EXCEL~FILEUPLOAD.
    METHODS FILEDOWNLOAD FOR MODIFY
      IMPORTING KEYS FOR ACTION EXCEL~FILEDOWNLOAD RESULT RESULT.
    METHODS VALIDATECUSTOMER FOR VALIDATE ON SAVE
      IMPORTING KEYS FOR EXCEL~VALIDATECUSTOMER.
    METHODS PRECHECK_CREATE FOR PRECHECK
      IMPORTING ENTITIES FOR CREATE EXCEL.
ENDCLASS.

CLASS LHC_ZRAP_I_EXCEL IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD FILEUPLOAD.

    DATA LT_UPLOAD TYPE STANDARD TABLE OF TY_FILE.
    DATA LT_CREATE TYPE TABLE FOR CREATE ZRAP_I_EXCEL.

    "READ TABLE KEYS ASSIGNING FIELD-SYMBOL(<KEY>) INDEX 1.
    ASSIGN KEYS[ 1 ] TO FIELD-SYMBOL(<KEY>).
    CHECK SY-SUBRC = 0.

    CHECK <KEY>-%PARAM-FILEEXTENSION = 'xlsx'.

    DATA(LV_FILE_CONTENT) = <KEY>-%PARAM-FILECONTENT.
    DATA(LO_READ_ACCESS) = XCO_CP_XLSX=>DOCUMENT->FOR_FILE_CONTENT( LV_FILE_CONTENT )->READ_ACCESS( ).
    DATA(LO_WORKSHEET) = LO_READ_ACCESS->GET_WORKBOOK( )->WORKSHEET->FOR_NAME( 'Sheet1' ).
    DATA(LO_SELECTION) = XCO_CP_XLSX_SELECTION=>PATTERN_BUILDER->SIMPLE_FROM_TO( )->FROM_COLUMN(
                            XCO_CP_XLSX=>COORDINATE->FOR_ALPHABETIC_VALUE( 'A' ) )->TO_COLUMN(
                            XCO_CP_XLSX=>COORDINATE->FOR_ALPHABETIC_VALUE( 'B' ) )->FROM_ROW(
                            XCO_CP_XLSX=>COORDINATE->FOR_NUMERIC_VALUE( 2 ) )->GET_PATTERN( ).

    LO_WORKSHEET->SELECT( LO_SELECTION )->ROW_STREAM( )->OPERATION->WRITE_TO(
                    REF #( LT_UPLOAD ) )->SET_VALUE_TRANSFORMATION(
                    XCO_CP_XLSX_READ_ACCESS=>VALUE_TRANSFORMATION->STRING_VALUE
                    )->IF_XCO_XLSX_RA_OPERATION~EXECUTE( ).

    CHECK LT_UPLOAD IS NOT INITIAL.
    LT_CREATE = CORRESPONDING #( LT_UPLOAD ).

    READ ENTITIES OF ZRAP_I_EXCEL IN LOCAL MODE
      ENTITY EXCEL
        FIELDS ( CUSTOMER )
        WITH CORRESPONDING #( KEYS )
      RESULT DATA(LT_EXCEL).

    SELECT FROM ZRAP_EXCEL FIELDS CUSTOMER
      FOR ALL ENTRIES IN @LT_UPLOAD
      WHERE CUSTOMER = @LT_UPLOAD-CUSTOMER
      INTO TABLE @DATA(LT_CUSTOMERS).

    LOOP AT LT_UPLOAD INTO DATA(LS_UPLOAD).
      IF LINE_EXISTS( LT_CUSTOMERS[ CUSTOMER = LS_UPLOAD-CUSTOMER  ] ).
        APPEND VALUE #( %CID = 'cid' && SY-TABIX ) TO FAILED-EXCEL.

        APPEND VALUE #( %CID = 'cid' && SY-TABIX
                        %STATE_AREA         = 'VALIDATE_AGENCY'
                        %MSG                = NEW /DMO/CM_FLIGHT_MESSAGES(
                                                          TEXTID   = /DMO/CM_FLIGHT_MESSAGES=>ENTER_AGENCY_ID
                                                          SEVERITY = IF_ABAP_BEHV_MESSAGE=>SEVERITY-ERROR )
                        %ELEMENT-CUSTOMER   = IF_ABAP_BEHV=>MK-ON
                       ) TO REPORTED-EXCEL.
      ENDIF.
    ENDLOOP.

*    LOOP AT LT_CREATE ASSIGNING FIELD-SYMBOL(<CREATE>).
*      <CREATE>-%CID = 'cid' && SY-TABIX.
*    ENDLOOP.

    MODIFY ENTITIES OF ZRAP_I_EXCEL IN LOCAL MODE
      ENTITY EXCEL
        CREATE FIELDS ( CUSTOMER ARTICLE ) AUTO FILL CID
        WITH LT_CREATE
        REPORTED DATA(LT_REPORT)
        FAILED DATA(LT_FAILED).

  ENDMETHOD.


  METHOD FILEDOWNLOAD.
*    DATA LT_DOWNLOAD TYPE STANDARD TABLE OF TY_FILE WITH DEFAULT KEY.
*    DATA LS_DOWNLOAD TYPE TY_FILE.

    DATA(LO_WRITE_ACCESS) = XCO_CP_XLSX=>DOCUMENT->EMPTY( )->WRITE_ACCESS( ).
    DATA(LO_WORKSHEET) = LO_WRITE_ACCESS->GET_WORKBOOK( )->WORKSHEET->AT_POSITION( 1 ).
    LO_WORKSHEET->SET_NAME( 'test' ).
    DATA(LO_SELECTION) = XCO_CP_XLSX_SELECTION=>PATTERN_BUILDER->SIMPLE_FROM_TO( )->FROM_COLUMN(
                            XCO_CP_XLSX=>COORDINATE->FOR_ALPHABETIC_VALUE( 'A' ) )->TO_COLUMN(
                            XCO_CP_XLSX=>COORDINATE->FOR_ALPHABETIC_VALUE( 'B' ) )->FROM_ROW(
                            XCO_CP_XLSX=>COORDINATE->FOR_NUMERIC_VALUE( 1 ) )->GET_PATTERN( ).

    DATA(LT_DOWNLOAD) = VALUE TT_FILE( ( CUSTOMER = 'Customer' ARTICLE  = 'Article' ) ).

    LO_WORKSHEET->SELECT( LO_SELECTION )->ROW_STREAM( )->OPERATION->WRITE_FROM(
                    REF #( LT_DOWNLOAD ) )->EXECUTE( ).
    DATA(LV_FILE_CONTENT) = LO_WRITE_ACCESS->GET_FILE_CONTENT( ).
    RESULT = VALUE #( FOR KEY IN KEYS (
                        %CID    = KEY-%CID
                        %PARAM  = VALUE #( FILECONTENT    = LV_FILE_CONTENT
                                           FILENAME       = 'Download_Template'
                                           FILEEXTENSION  = 'xlsx'
                                           MIMETYPE       = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' ) )
                    ).
  ENDMETHOD.

  METHOD VALIDATECUSTOMER.
  ENDMETHOD.

  METHOD PRECHECK_CREATE.
  ENDMETHOD.
ENDCLASS.
